language: node_js

node_js:
  - "stable"

notifications:
  email: false

cache:
  directories:
  - node_modules

script:
  npm run build

install:
  - yarn

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $Travis CI
  local_dir: build
  on:
    branch: master