name: Release

on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: |
          npm ci
          npm run setup

      - name: Setup Build 🚀
        run: npm run pack

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npx lerna publish --conventional-commits --yes